#!/usr/bin/env python3
"""
TR-909 Sample Organization

Organizes TR-909 samples into GM Standard structure for SF2 creation.
The TR-909 has ~120 samples organized in folders by instrument type.
"""

import os
import shutil
from pathlib import Path

SOURCE_DIR = "/Volumes/Storage/samples/Roland - JeuneLys_Beatz/ROLAND_TR-909_(1983)"
BUILD_DIR = "piano_workshop/piano_workshop/build/drum_kits/tr909_gm"

def organize_909():
    """Organize TR-909 samples with proper GM mapping"""
    print("🥁 Organizing TR-909 samples...")

    src = Path(SOURCE_DIR)
    dest = Path(BUILD_DIR)

    if not src.exists():
        print(f"❌ Source not found: {SOURCE_DIR}")
        return False

    # Create destination directories
    dest.mkdir(parents=True, exist_ok=True)

    # TR-909 instrument folders
    instrument_map = {
        "Kicks": "kick",
        "Snares": "snare",
        "Closed_Hats": "closed_hat",
        "Open_Hats": "open_hat",
        "Toms": "tom",
        "Claps": "clap",
        "Crash": "crash",
        "Ride": "ride",
        "Rim_Shots": "rimshot",
    }

    # Create instrument directories
    for inst in instrument_map.values():
        (dest / inst).mkdir(exist_ok=True)

    total_copied = 0

    # Copy and organize samples
    for src_folder, inst_name in instrument_map.items():
        src_path = src / src_folder
        if not src_path.exists():
            print(f"  ⚠️  Folder not found: {src_folder}")
            continue

        # Copy all WAV files from this folder
        wav_count = 0
        for wav_file in src_path.glob("*.wav"):
            # Create simplified GM name
            new_name = simplify_909_filename(wav_file.name, inst_name)
            dest_file = dest / inst_name / new_name

            # Skip if already exists
            if dest_file.exists():
                continue

            shutil.copy2(wav_file, dest_file)
            total_copied += 1
            wav_count += 1

        print(f"  ✅ {inst_name:12}: {wav_count:3} samples")

    print(f"\n✅ TR-909 organized: {total_copied} samples copied")
    return True

def simplify_909_filename(original: str, instrument: str) -> str:
    """Convert TR-909 filename to simple GM naming"""
    ext = ".wav"

    # Extract variant number
    if "01" in original or "02" in original or "03" in original:
        variant = "_v1"
    elif "04" in original or "05" in original or "06" in original:
        variant = "_v2"
    elif "07" in original or "08" in original or "09" in original:
        variant = "_v3"
    elif "10" in original:
        variant = "_v4"
    else:
        variant = ""

    # GM naming for TR-909
    gm_names = {
        "kick": "909_kick_c1",
        "snare": "909_snare_d1",
        "closed_hat": "909_ch_fsharp1",
        "open_hat": "909_oh_asharp1",
        "tom": "909_tom",  # Will number individually
        "clap": "909_clap_dsharp1",
        "crash": "909_crash",
        "ride": "909_ride",
        "rimshot": "909_rimshot_csharp1",
    }

    base = gm_names.get(instrument, instrument)
    return f"{base}{variant}{ext}"

def generate_909_sfz():
    """Generate SFZ file for TR-909"""
    print("\n📝 Generating TR-909 SFZ...")

    dest = Path(BUILD_DIR)
    sfz_file = dest / "roland_tr909.sfz"

    # Count samples per directory
    sample_counts = {}
    for inst_dir in dest.iterdir():
        if inst_dir.is_dir():
            count = len(list(inst_dir.glob("*.wav")))
            sample_counts[inst_dir.name] = count

    sfz_content = """// Roland TR-909 GM Standard Mapping
// Generated by organize_909.py

// Control defaults
<control> set_cc7=127 // Volume

// Global settings
<global>
ampeg_attack=0.001
ampeg_decay=0.1
ampeg_sustain=100
ampeg_release=0.3

// Kick (C1, MIDI 36) - Bass Drum 1
<region> sample=kick/909_kick_c1_v1.wav lokey=36 hikey=36 lovel=0 hivel=31 pitch_keycenter=36 ampeg_release=0.5
<region> sample=kick/909_kick_c1_v2.wav lokey=36 hikey=36 lovel=32 hivel=63 pitch_keycenter=36 ampeg_release=0.45
<region> sample=kick/909_kick_c1_v3.wav lokey=36 hikey=36 lovel=64 hivel=95 pitch_keycenter=36 ampeg_release=0.4
<region> sample=kick/909_kick_c1_v4.wav lokey=36 hikey=36 lovel=96 hivel=127 pitch_keycenter=36 ampeg_release=0.35

// Snare (D1, MIDI 38) - Snare Drum 1
<region> sample=snare/909_snare_d1_v1.wav lokey=38 hikey=38 lovel=0 hivel=31 pitch_keycenter=38 ampeg_release=0.25
<region> sample=snare/909_snare_d1_v2.wav lokey=38 hikey=38 lovel=32 hivel=63 pitch_keycenter=38 ampeg_release=0.22
<region> sample=snare/909_snare_d1_v3.wav lokey=38 hikey=38 lovel=64 hivel=95 pitch_keycenter=38 ampeg_release=0.20
<region> sample=snare/909_snare_d1_v4.wav lokey=38 hikey=38 lovel=96 hivel=127 pitch_keycenter=38 ampeg_release=0.18

// Closed Hi-Hat (F#1, MIDI 42)
<region> sample=closed_hat/909_ch_fsharp1_v1.wav lokey=42 hikey=42 lovel=0 hivel=63 pitch_keycenter=42 ampeg_release=0.12
<region> sample=closed_hat/909_ch_fsharp1_v2.wav lokey=42 hikey=42 lovel=64 hivel=127 pitch_keycenter=42 ampeg_release=0.10

// Open Hi-Hat (A#1, MIDI 46)
<region> sample=open_hat/909_oh_asharp1_v1.wav lokey=46 hikey=46 lovel=0 hivel=63 pitch_keycenter=46 ampeg_release=0.4
<region> sample=open_hat/909_oh_asharp1_v2.wav lokey=46 hikey=46 lovel=64 hivel=127 pitch_keycenter=46 ampeg_release=0.35

// Hand Clap (D#1, MIDI 39)
<region> sample=clap/909_clap_dsharp1_v1.wav lokey=39 hikey=39 lovel=0 hivel=63 pitch_keycenter=39 ampeg_release=0.15
<region> sample=clap/909_clap_dsharp1_v2.wav lokey=39 hikey=39 lovel=64 hivel=127 pitch_keycenter=39 ampeg_release=0.12

// Rim Shot (C#1, MIDI 37)
<region> sample=rimshot/909_rimshot_csharp1_v1.wav lokey=37 hikey=37 lovel=0 hivel=63 pitch_keycenter=37 ampeg_release=0.12
<region> sample=rimshot/909_rimshot_csharp1_v2.wav lokey=37 hikey=37 lovel=64 hivel=127 pitch_keycenter=37 ampeg_release=0.10

// Crash Cymbal (48, MIDI 48)
<region> sample=crash/909_crash_v1.wav lokey=48 hikey=48 lovel=0 hivel=63 pitch_keycenter=48 ampeg_release=0.8
<region> sample=crash/909_crash_v2.wav lokey=48 hikey=48 lovel=64 hivel=127 pitch_keycenter=48 ampeg_release=0.7

// Ride Cymbal (49, MIDI 49)
<region> sample=ride/909_ride_v1.wav lokey=49 hikey=49 lovel=0 hivel=63 pitch_keycenter=49 ampeg_release=0.6
<region> sample=ride/909_ride_v2.wav lokey=49 hikey=49 lovel=64 hivel=127 pitch_keycenter=49 ampeg_release=0.5
"""

    with open(sfz_file, "w") as f:
        f.write(sfz_content)

    print(f"✅ SFZ created: {sfz_file}")
    print(f"\n📊 Sample counts:")
    for inst, count in sorted(sample_counts.items()):
        print(f"  {inst}: {count} samples")

    return True

def main():
    print("=" * 70)
    print("TR-909 Sample Organization")
    print("=" * 70)
    print()

    # Step 1: Copy samples
    if organize_909():
        # Step 2: Generate SFZ
        generate_909_sfz()

        print()
        print("=" * 70)
        print("✅ TR-909 ready for SF2 creation!")
        print("=" * 70)
        print()
        print("Next steps:")
        print("1. Open Polyphone")
        print("2. File → Import → SFZ")
        print(f"3. Select: {BUILD_DIR}/roland_tr909.sfz")
        print("4. File → Export → SoundFont2")
        print("5. Save as: piano_workshop/dist/drum_kits/roland_tr909.sf2")

if __name__ == "__main__":
    main()
