#!/usr/bin/env python3
"""
TR-808 Sample Organization - Fixed Version

Properly handles TR-808 naming convention and copies all samples.
"""

import os
import shutil
from pathlib import Path

SOURCE_DIR = "/Volumes/Storage/samples/Roland - JeuneLys_Beatz/ROLAND_TR-808_(1980)"
BUILD_DIR = "piano_workshop/piano_workshop/build/drum_kits/tr808_gm"

def organize_808_fixed():
    """Organize TR-808 samples with proper handling of actual filenames"""
    print("🎸 Organizing TR-808 samples (FIXED VERSION)...")

    src = Path(SOURCE_DIR)
    dest = Path(BUILD_DIR)

    if not src.exists():
        print(f"❌ Source not found: {SOURCE_DIR}")
        return False

    # Create destination directories
    dest.mkdir(parents=True, exist_ok=True)

    instrument_dirs = {
        "kick": ["[BD]_Bass_Drum_(808s)", "[BD]_Bass_Drum_(Kick)"],
        "snare": ["[SD]_Snare_Drum"],
        "closed_hat": ["[CH]_Closed_Hat"],
        "open_hat": ["[OH]_Open_Hat"],
        "tom_low": ["[LT]_Low_Tom"],
        "tom_mid": ["[MT]_Mid_Tom"],
        "tom_high": ["[HT]_Hi_Tom"],
        "clap": ["[CP]_Hand_Clap"],
        "cowbell": ["[CB]_Cowbell"],
        "conga": ["[LC]_Low_Conga", "[MC]_Mid_Conga", "[HC]_Hi_Conga"],
        "cymbal": ["[CY]_Cymbal"],
        "rimshot": ["[RS]_Rim_Shot"],
        "clave": ["[CL]_Clave"],
        "maracas": ["[MA]_Maracas"],
    }

    # Create instrument directories
    for inst in instrument_dirs.keys():
        (dest / inst).mkdir(exist_ok=True)

    total_copied = 0

    # Copy samples with simplified names
    for inst_name, src_folders in instrument_dirs.items():
        for src_folder in src_folders:
            src_path = src / src_folder
            if not src_path.exists():
                continue

            # Copy all WAV files
            for wav_file in src_path.glob("*.wav"):
                # Create simplified filename
                new_name = simplify_808_filename(wav_file.name, inst_name)
                dest_file = dest / inst_name / new_name

                # Skip if already exists
                if dest_file.exists():
                    continue

                shutil.copy2(wav_file, dest_file)
                total_copied += 1
                print(f"  Copied: {wav_file.name} → {inst_name}/{new_name}")

    print(f"\n✅ TR-808 organized: {total_copied} samples copied")
    return True

def simplify_808_filename(original: str, instrument: str) -> str:
    """Convert TR-808 filename to simple GM naming"""

    # Keep extension
    ext = ".wav"

    # Extract any velocity layer info
    if "01" in original or "02" in original:
        variant = "_v1"
    elif "03" in original or "04" in original:
        variant = "_v2"
    elif "05" in original or "06" in original:
        variant = "_v3"
    else:
        variant = ""

    # GM naming
    gm_names = {
        "kick": "808_kick_c1",
        "snare": "808_snare_d1",
        "closed_hat": "808_ch_fsharp1",
        "open_hat": "808_oh_asharp1",
        "tom_low": "808_tom1_g1",
        "tom_mid": "808_tom2_a1",
        "tom_high": "808_tom3_b1",
        "clap": "808_clap_dsharp1",
        "cowbell": "808_cowbell_gsharp1",
        "conga": "808_conga",
        "cymbal": "808_cymbal",
        "rimshot": "808_rimshot_csharp1",
        "clave": "808_clave",
        "maracas": "808_maracas",
    }

    base = gm_names.get(instrument, instrument)
    return f"{base}{variant}{ext}"

def generate_808_sfz():
    """Generate SFZ file for TR-808"""
    print("\n📝 Generating TR-808 SFZ...")

    dest = Path(BUILD_DIR)
    sfz_file = dest / "roland_tr808.sfz"

    # Count actual samples in each directory
    sample_counts = {}
    for inst_dir in dest.iterdir():
        if inst_dir.is_dir():
            count = len(list(inst_dir.glob("*.wav")))
            sample_counts[inst_dir.name] = count

    sfz_content = """// Roland TR-808 GM Standard Mapping
// Generated by organize_808_fixed.py

// Control defaults
<control> set_cc7=127 // Volume

// Global settings
<global>
ampeg_attack=0.001
ampeg_decay=0.1
ampeg_sustain=100
ampeg_release=0.3

// Kick (C1, MIDI 36) - Bass Drum 1
<region> sample=kick/808_kick_c1_v1.wav lokey=36 hikey=36 lovel=0 hivel=42 pitch_keycenter=36 ampeg_release=0.6
<region> sample=kick/808_kick_c1_v2.wav lokey=36 hikey=36 lovel=43 hivel=84 pitch_keycenter=36 ampeg_release=0.5
<region> sample=kick/808_kick_c1_v3.wav lokey=36 hikey=36 lovel=85 hivel=127 pitch_keycenter=36 ampeg_release=0.4

// Snare (D1, MIDI 38) - Snare Drum 1
<region> sample=snare/808_snare_d1_v1.wav lokey=38 hikey=38 lovel=0 hivel=42 pitch_keycenter=38 ampeg_release=0.3
<region> sample=snare/808_snare_d1_v2.wav lokey=38 hikey=38 lovel=43 hivel=127 pitch_keycenter=38 ampeg_release=0.25

// Closed Hi-Hat (F#1, MIDI 42)
<region> sample=closed_hat/808_ch_fsharp1.wav lokey=42 hikey=42 pitch_keycenter=42 ampeg_release=0.15

// Open Hi-Hat (A#1, MIDI 46)
<region> sample=open_hat/808_oh_asharp1.wav lokey=46 hikey=46 pitch_keycenter=46 ampeg_release=0.5

// Low Tom (G1, MIDI 43)
<region> sample=tom_low/808_tom1_g1.wav lokey=43 hikey=43 pitch_keycenter=43 ampeg_release=0.4

// Mid Tom (A1, MIDI 45)
<region> sample=tom_mid/808_tom2_a1.wav lokey=45 hikey=45 pitch_keycenter=45 ampeg_release=0.35

// High Tom (B1, MIDI 47)
<region> sample=tom_high/808_tom3_b1.wav lokey=47 hikey=47 pitch_keycenter=47 ampeg_release=0.3

// Hand Clap (D#1, MIDI 39)
<region> sample=clap/808_clap_dsharp1.wav lokey=39 hikey=39 pitch_keycenter=39 ampeg_release=0.2

// Cowbell (G#1, MIDI 56)
<region> sample=cowbell/808_cowbell_gsharp1.wav lokey=56 hikey=56 pitch_keycenter=56 ampeg_release=0.3

// Rim Shot (C#1, MIDI 37)
<region> sample=rimshot/808_rimshot_csharp1.wav lokey=37 hikey=37 pitch_keycenter=37 ampeg_release=0.15

// Clave (B0, MIDI 35)
<region> sample=clave/808_clave.wav lokey=35 hikey=35 pitch_keycenter=35 ampeg_release=0.2

// Maracas (C#2, MIDI 49)
<region> sample=maracas/808_maracas.wav lokey=49 hikey=49 pitch_keycenter=49 ampeg_release=0.15
"""

    with open(sfz_file, "w") as f:
        f.write(sfz_content)

    print(f"✅ SFZ created: {sfz_file}")
    print(f"\n📊 Sample counts:")
    for inst, count in sorted(sample_counts.items()):
        print(f"  {inst}: {count} samples")

    return True

def main():
    print("=" * 70)
    print("TR-808 Sample Organization - Fixed Version")
    print("=" * 70)
    print()

    # Step 1: Copy samples
    if organize_808_fixed():
        # Step 2: Generate SFZ
        generate_808_sfz()

        print()
        print("=" * 70)
        print("✅ TR-808 ready for SF2 creation!")
        print("=" * 70)
        print()
        print("Next steps:")
        print("1. Install Polyphone: brew install --cask polyphone")
        print("2. Open Polyphone")
        print("3. File → Import → SFZ")
        print(f"4. Select: {BUILD_DIR}/roland_tr808.sfz")
        print("5. File → Export → SoundFont2")
        print("6. Save as: piano_workshop/dist/drum_kits/roland_tr808.sf2")

if __name__ == "__main__":
    main()
