#!/usr/bin/env python3
"""
TR-626 Sample Organization

Organizes TR-626 samples into GM Standard structure for SF2 creation.
"""

import os
import shutil
from pathlib import Path

SOURCE_DIR = "/Volumes/Storage/samples/Roland - JeuneLys_Beatz/ROLAND_TR-626_(1987)"
BUILD_DIR = "piano_workshop/build/drum_kits/tr626_gm"

def organize_626():
    """Organize TR-626 samples with proper GM mapping"""
    print("🥁 Organizing TR-626 samples...")

    src = Path(SOURCE_DIR)
    dest = Path(BUILD_DIR)

    if not src.exists():
        print(f"❌ Source not found: {SOURCE_DIR}")
        return False

    # Create destination directories
    dest.mkdir(parents=True, exist_ok=True)

    # TR-626 instrument folders
    instrument_map = {
        "Kick": "kick",
        "Snare": "snare",
        "Hi_Hat": "closed_hat",
        "Cymbals": "cymbal",
        "Tom": "tom",
        "Clap": "clap",
        "Rim_Shot": "rimshot",
        "Percs": "percussion",
    }

    # Create instrument directories
    for inst in instrument_map.values():
        (dest / inst).mkdir(exist_ok=True)

    total_copied = 0

    # Copy and organize samples
    for src_folder, inst_name in instrument_map.items():
        src_path = src / src_folder
        if not src_path.exists():
            print(f"  ⚠️  Folder not found: {src_folder}")
            continue

        # Copy all WAV files from this folder
        wav_count = 0
        for wav_file in src_path.glob("*.wav"):
            # Create simplified GM name
            new_name = simplify_626_filename(wav_file.name, inst_name)
            dest_file = dest / inst_name / new_name

            # Skip if already exists
            if dest_file.exists():
                continue

            shutil.copy2(wav_file, dest_file)
            total_copied += 1
            wav_count += 1

        print(f"  ✅ {inst_name:12}: {wav_count:3} samples")

    print(f"\n✅ TR-626 organized: {total_copied} samples copied")
    return True

def simplify_626_filename(original: str, instrument: str) -> str:
    """Convert TR-626 filename to simple GM naming"""
    ext = ".wav"

    # Extract variant number from filename
    if any(char.isdigit() for char in original):
        # Find first digit
        for i, char in enumerate(original):
            if char.isdigit():
                variant_num = int(char)
                if variant_num <= 3:
                    variant = f"_v{variant_num}"
                else:
                    variant = ""
                break
    else:
        variant = ""

    # GM naming for TR-626
    gm_names = {
        "kick": "626_kick_c1",
        "snare": "626_snare_d1",
        "closed_hat": "626_ch_fsharp1",
        "cymbal": "626_cymbal",
        "tom": "626_tom",
        "clap": "626_clap_dsharp1",
        "rimshot": "626_rimshot_csharp1",
        "percussion": "626_perc",
    }

    base = gm_names.get(instrument, instrument)
    return f"{base}{variant}{ext}"

def generate_626_sfz():
    """Generate SFZ file for TR-626"""
    print("\n📝 Generating TR-626 SFZ...")

    dest = Path(BUILD_DIR)
    sfz_file = dest / "roland_tr626.sfz"

    # Count samples per directory
    sample_counts = {}
    for inst_dir in dest.iterdir():
        if inst_dir.is_dir():
            count = len(list(inst_dir.glob("*.wav")))
            sample_counts[inst_dir.name] = count

    sfz_content = """// Roland TR-626 GM Standard Mapping
// Generated by organize_626.py

// Control defaults
<control> set_cc7=127 // Volume

// Global settings
<global>
ampeg_attack=0.001
ampeg_decay=0.1
ampeg_sustain=100
ampeg_release=0.3

// Kick (C1, MIDI 36) - Bass Drum 1
<region> sample=kick/626_kick_c1_v1.wav lokey=36 hikey=36 lovel=0 hivel=42 pitch_keycenter=36 ampeg_release=0.4
<region> sample=kick/626_kick_c1_v2.wav lokey=36 hikey=36 lovel=43 hivel=84 pitch_keycenter=36 ampeg_release=0.35
<region> sample=kick/626_kick_c1_v3.wav lokey=36 hikey=36 lovel=85 hivel=127 pitch_keycenter=36 ampeg_release=0.3

// Snare (D1, MIDI 38) - Snare Drum 1
<region> sample=snare/626_snare_d1_v1.wav lokey=38 hikey=38 lovel=0 hivel=42 pitch_keycenter=38 ampeg_release=0.2
<region> sample=snare/626_snare_d1_v2.wav lokey=38 hikey=38 lovel=43 hivel=127 pitch_keycenter=38 ampeg_release=0.18

// Closed Hi-Hat (F#1, MIDI 42)
<region> sample=closed_hat/626_ch_fsharp1_v1.wav lokey=42 hikey=42 lovel=0 hivel=42 pitch_keycenter=42 ampeg_release=0.15
<region> sample=closed_hat/626_ch_fsharp1_v2.wav lokey=42 hikey=42 lovel=43 hivel=127 pitch_keycenter=42 ampeg_release=0.12

// Cymbal
<region> sample=cymbal/626_cymbal_v1.wav lokey=49 hikey=49 lovel=0 hivel=63 pitch_keycenter=49 ampeg_release=0.6
<region> sample=cymbal/626_cymbal_v2.wav lokey=49 hikey=49 lovel=64 hivel=127 pitch_keycenter=49 ampeg_release=0.5

// Tom (G1, MIDI 43) - Low Tom
<region> sample=tom/626_tom_v1.wav lokey=43 hikey=43 lovel=0 hivel=42 pitch_keycenter=43 ampeg_release=0.25
<region> sample=tom/626_tom_v2.wav lokey=43 hikey=43 lovel=43 hivel=127 pitch_keycenter=43 ampeg_release=0.2

// Rim Shot (C#1, MIDI 37)
<region> sample=rimshot/626_rimshot_csharp1_v1.wav lokey=37 hikey=37 lovel=0 hivel=63 pitch_keycenter=37 ampeg_release=0.12
<region> sample=rimshot/626_rimshot_csharp1_v2.wav lokey=37 hikey=37 lovel=64 hivel=127 pitch_keycenter=37 ampeg_release=0.10

// Hand Clap (D#1, MIDI 39)
<region> sample=clap/626_clap_dsharp1_v1.wav lokey=39 hikey=39 lovel=0 hivel=63 pitch_keycenter=39 ampeg_release=0.15
<region> sample=clap/626_clap_dsharp1_v2.wav lokey=39 hikey=39 lovel=64 hivel=127 pitch_keycenter=39 ampeg_release=0.12
"""

    with open(sfz_file, "w") as f:
        f.write(sfz_content)

    print(f"✅ SFZ created: {sfz_file}")
    print(f"\n📊 Sample counts:")
    for inst, count in sorted(sample_counts.items()):
        print(f"  {inst}: {count} samples")

    return True

def main():
    print("=" * 70)
    print("TR-626 Sample Organization")
    print("=" * 70)
    print()

    # Step 1: Copy samples
    if organize_626():
        # Step 2: Generate SFZ
        generate_626_sfz()

        print()
        print("=" * 70)
        print("✅ TR-626 ready for SF2 creation!")
        print("=" * 70)
        print()
        print("Next steps:")
        print("1. Open Polyphone")
        print("2. File → Import → SFZ")
        print(f"3. Select: {BUILD_DIR}/roland_tr626.sfz")
        print("4. File → Export → SoundFont2")
        print("5. Save as: piano_workshop/dist/drum_kits/roland_tr626.sf2")

if __name__ == "__main__":
    main()
